/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gail_jha;

import static gail_jha.Main_Pager.con;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author shivam
 */
public class addCom extends javax.swing.JFrame {

    /**
     * Creates new form addCom
     * @throws java.io.IOException
     */
    public addCom() throws IOException {
        initComponents(); 
            setLocationRelativeTo(null);
        jComboBox2.removeAllItems();
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/GAIL_logo.gif")));
            setLocationRelativeTo(null);
        try {
            Statement st = con.createStatement();
            ResultSet rs ;
            String sql = "select name from typ";
            rs = st.executeQuery(sql);
            while(rs.next()){
                String s1 = rs.getString(1);
                jComboBox2.addItem(s1);
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(addCom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Complaint");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel1.setText("Location : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 120, 90, 15));

        jLabel2.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel2.setText("Type :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 170, 60, 15));

        jLabel3.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel3.setText("Description :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 15));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 253, 121));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RR Station","Compressor","Colony" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 233, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"DEMO COMPLAIN ! -101","DEMO COMPLAIN !","DEMO COMPLAIN !","DEMO COMPLAIN !","DEMO COMPLAIN !","DEMO COMPLAIN !",}));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 233, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText(" *");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel4.setText("Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 30, 70, 15));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 29, 223, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText(" *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel12.setText("Max 255 Character");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("* Field can not be empty");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel5.setText("Comment (if any) :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 15));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(4);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 250, 84));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel11.setText("Max 255 Character");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel6.setText("Mobile No. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 60, 100, 15));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 60, 223, -1));

        jLabel7.setFont(new java.awt.Font("Lato Heavy", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffffe0-a-300-f-14.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String loc = (String) jComboBox1.getSelectedItem();
        String com;
        com = (String) jComboBox2.getSelectedItem();
        int sta = 0;
        int flag = 0;
        String mob = jTextField2.getText();
        mob = mob.trim();
        String ack = "";
        String name = jTextField1.getText();
        String des = jTextArea1.getText();
        String comment = jTextArea2.getText();
        name = name.trim();
        des = des.trim();
        comment = comment.trim();
       if(des.isEmpty()||name.isEmpty()){
       JOptionPane.showMessageDialog(this, "Field Can'nt Be Empty");
       flag = 1;
       }
       if(des.length()>255||comment.length()>255)
           JOptionPane.showMessageDialog(this, "Character Limit is 255 ");
        flag = chknm(name);
       if(flag == 0){
        try {
            PreparedStatement st = con.prepareStatement("insert into main_db (ack,dt,st,cid,pid,des,name,comment,mobile)values(?,?,?,?,?,?,?,?,?)");
            ResultSet rs = st.executeQuery("select id from main_db order by id desc limit 1");
            int id;
            if(rs.next()){
              id = rs.getInt(1);
              id++;
            }
            else
               id=1;
            rs.close();
            String date = new SimpleDateFormat("dd/MM/YYYY").format(new java.util.Date());
            ack = date+"/"+id;
            date = new SimpleDateFormat("dd-MM-YYYY").format(new java.util.Date());
            st.setString(1, ack);
            st.setString(2, date);
            st.setInt(3, sta);
            st.setString(4, com);
            st.setString(5, loc);
            st.setString(6, des);
            st.setString(7, name);
            st.setString(8, comment);
            st.setString(9, mob);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this,  "Please Copy Your ACK No. for Further Assistence : "+ack);
            
            this.dispose();
        } catch (SQLException ex) {
                       JOptionPane.showMessageDialog(this, "Error 108");
            Logger.getLogger(addCom.class.getName()).log(Level.SEVERE, null, ex);
        }}
       else
           JOptionPane.showMessageDialog(this, "Something Went Wrong! ECodev : "+flag);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
//addCom a = new addCom();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addCom().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(addCom.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private int chknm(String name) {
    //    CharSequence CharSequence = CharSequence; 
      
        if(name.length()!=0){
        Pattern special = Pattern.compile ("[!@#$%&*()_+=|<>?{}\\[\\]~-]");
        Matcher ch  = special.matcher(name);
        if(ch.find()==true){
            JOptionPane.showMessageDialog(this, "Name Can not Contains Special Character");
            return 2;
            }
        }
        else
         return 2;
        return 0;
    }
}
